controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [kr210_joint_a1, kr210_joint_a2, kr210_joint_a3, kr210_joint_a4, kr210_joint_a5, kr210_joint_a6]
