# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  kr210_joint_a1:
    has_velocity_limits: true
    max_velocity: 2.14675497995
    has_acceleration_limits: false
    max_acceleration: 0
  kr210_joint_a2:
    has_velocity_limits: true
    max_velocity: 2.00712863979
    has_acceleration_limits: false
    max_acceleration: 0
  kr210_joint_a3:
    has_velocity_limits: true
    max_velocity: 1.95476876223
    has_acceleration_limits: false
    max_acceleration: 0
  kr210_joint_a4:
    has_velocity_limits: true
    max_velocity: 3.12413936107
    has_acceleration_limits: false
    max_acceleration: 0
  kr210_joint_a5:
    has_velocity_limits: true
    max_velocity: 3.00196631343
    has_acceleration_limits: false
    max_acceleration: 0
  kr210_joint_a6:
    has_velocity_limits: true
    max_velocity: 3.82227106187
    has_acceleration_limits: false
    max_acceleration: 0